name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull karthikrajadatasack/itstaffaugmentation-app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f itstaffaugmentation-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8081:8080 --name itstaffaugmentation-app-container karthikrajadatasack/itstaffaugmentation-app
      # after docker successfull run, need to clean the old images. called dangling images
    - name: Clean up dangling images 
      run: sudo docker image prune -f