name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
    - name: Pull Docker image
      run: sudo docker pull karthikrajadatasack/itstaffaugmentation-app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f itstaffaugmentation-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8081:8080 --name itstaffaugmentation-app-container karthikrajadatasack/itstaffaugmentation-app
      # after docker successfull run, need to clean the old images. called dangling images
    - name: Clean up dangling images 
      run: sudo docker image prune -f